# Aws Region
region="us-west-2"

# Override AMI id
#ami="ami-d926ebb9"

# define VPC base !
#vpc-base="172.31"
# then the rest of these lame settings can get defaulted to /16 and /24

# VPC address range.  Eg. A range between  172.16.0.0 - 172.31.255.255 
vpc-cidr-block="172.31.0.0/16"

# Subnets
num-subnets=3
subnet-0-cidr="172.31.0.0/24"
subnet-1-cidr="172.31.1.0/24"
subnet-2-cidr="172.31.2.0/24"

# Tag lookup using Tag=KubernetesCluster=Value
cluster-name="launch-default"

# The range kubernetes will use for the entire cluster.
cluster-cidr="10.244.0.0/16"

# The range kubernetes will use for all 'services'
service-cluster-ip-range="10.0.0.0/16"

# The service IP that kubernetes will use for DNS. Must be an address in the service-cluster-ip-range.
cluster-dns="10.0.0.10"

# Master Cluster Size
master-cluster-size="1"
master-instance-type="t2.micro"

# Minion Cluster Size
minion-cluster-size="1"
minion-instance-type="t2.micro"
# Minion Root Volume size (in Gigabytes)
minion-root-volume-size=100
